GET http://localhost:8080/login?username=luis&password=luis

> {%
    client.global.set("token", response.body.access_token)
%}
###
GET http://localhost:8080/register?username=hola21&password=hola21
###


GET http://localhost:8080/getAccessToken
    ?refreshtoken=
    eyJhbGciOiJSUzM4NCJ9.eyJzdWIiOiJsdWlzIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzA4NDQ0OTUwfQ.r5iQ1wAVjX3LHxk2zi0IsbAGYCRt4vDj4du-1A9etmUV3v3RjKYbkUofFuDx0MjxItVNMpE6IPcw8BHESR7Ok3ILONsrpQCo9TEhlDNV28QJ0WuFlHbwxVvu5CWrRodCQor8J6_6CppzvKHoEtRYWe17OckqhD_nXZPZF4DfTkwFQT4vVNKrjtmpsm2AcjYAC8lr3HwOGnJZcj_wVl0RT0kr9_BTxEiIG6GglQk6pUIqMu4hKnPcwJI09BXvJIZQtfylLhl4Dpv0YW8fPgehKcDVs_JKxd90r9MWMm4b68L7muLhgWeAh4II01zwZOF3_789SjkqFQE6RoRBsBXmOG8B3lx9UoBHNm0yJdIUPZf5R_yXknA2gPKQhM1Arhe3RlMYJeTHVrEeY2JEM5_kUb3ocqdeyId0MZ3QlCLj-bSu6uf-QGnhOZIJkp1aNJUc3Wtw58ijyFkSRe7geX8MDMIupI5-9RB6q8nkLi1FwQ9VjDmgQb2jC2tZaA24AnuW

###OrderItems


GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

mutation addOrderItem {
    addOrderItem(input:
    {
        name: "arrozyhuevo",
        price: 1.5,
        quantity: 10,
        orderId: 14}) {
        name
        orderItemId
        price
        quantity
    }
}


###
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

query  getOrderItemsByItem($idItem: Int) {
    getOrderItemsByItem(idItem: $idItem) {
        name
    }
}

{
  "idItem": 1
}
###
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

query  getOrderItemsByOrder($id: Int) {
    getOrderItemsByOrder(id: $id) {
        name
        quantity
        price
    }
}

{
  "id": 1
}
###Customers
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

mutation  updateCustomer {
    updateCustomer(
        input: {
            id: 2,
            firstName: "l",
            lastName: "l",
            email: "l",
            phone: "l",
            dateOfBirth:"2001-09-09",
            }
    ) {
        firstName
    }
}

###
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

query  getCustomers {
    getCustomers {
        firstName
    }
}
###
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

query  getCustomer($id: Int) {
    getCustomer(id: $id) {
        firstName
    }
}

{
  "id": 1
}

###
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}


mutation  deleteCustomer{
    deleteCustomer(idCustomer:7)
}

###
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

mutation  addCustomer {
    addCustomer(input: {
        firstName: "luisPrueba2",
        lastName: "luisPrueba2",
        email: "luisPrueba@example.com2",
        dateOfBirth: "2001-09-09",
        phone: "siPrueba"
    }) {
        id
        firstName
        lastName
        email
        dateOfBirth
        phone
    }
}
###Orders
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

query  {
    getAllOrders {
        orderId
    }
}

###
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

query  getOrdersDeCust($idCust: Int) {
    getOrdersDeCust(idCust: $idCust) {
        orderId
    }
}

{
  "idCust": 1
}
###
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

mutation saveOrder {
    saveOrder(input:
    {
        customerid: 2,
        orderDate: "2023-09-10T22:30:00"

    }) {
        orderId
    }
}
###
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

mutation  deleteOrder($idOrder: Int) {
    deleteOrder(idOrder: $idOrder)
}

{
  "idOrder": 14
}
###
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

query  getOrder($id: Int) {
    getOrder(id: $id) {
        orderId
        orderDate

    }
}

{
  "id": 2
}

###RestaurantTables
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

query getAllTablesByCust($idCust:Int){
    getAllTablesByCustomer(idCust: $idCust)
    {
     numberOfSeats
    }
}
{"idCust": 1
}

###Commands
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

query  getCommandsByCustomer($idCust: Int) {
getCommandsByCustomer(idCust: $idCust) {
commandName
}
}

{
   "idCust": 1
}


###Excepciones
###Logearse a un usuario que no existe
GET http://localhost:8080/login?username=holanoexisto&password=holanoexisto


###Registrarse con un nombre de usuario que ya existe
GET http://localhost:8080/register?username=luis&password=luis

###Introducir una id de otro elemento invalida

GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

mutation addOrderItem {
    addOrderItem(input:
    {
        name: "arrozyhuevo",
        price: 1.5,
        quantity: 10,
        orderId: 200}) {
        name
        orderItemId
        price
        quantity
    }
}


###Introducir una id  invalida
GRAPHQL http://localhost:8081/graphql
Authorization: Bearer {{token}}

query  getOrderItemsByItem($idItem: Int) {
    getOrderItemsByItem(idItem: $idItem) {
        name
    }
}

{
  "idItem": 211111
}